In [1]:
import cv2
import matplotlib.pyplot as plt

# Image Reading

In [2]:
#Reading the image as a coloured image
img1= cv2.imread("C:/Users/Open user/Documents/AWARRI collection 2/3_men.jpg", 1)
#print(img)

In [3]:
#Reading the image as a grayscale(black&white) image
img2= cv2.imread("C:/Users/Open user/Documents/AWARRI collection 2/3_men.jpg", 0)
img2

array([[60, 60, 60, ..., 57, 58, 53],
       [60, 60, 60, ..., 57, 60, 57],
       [60, 60, 60, ..., 57, 62, 60],
       ...,
       [40, 44, 48, ..., 54, 52, 52],
       [39, 45, 50, ..., 56, 56, 54],
       [41, 47, 52, ..., 56, 59, 58]], dtype=uint8)

In [4]:
print(type(img1))

<class 'numpy.ndarray'>


In [5]:
img1.shape

(1080, 1920, 3)

In [6]:
img2.shape

(1080, 1920)

# Image viewing

In [7]:
#Viewing the coloured image
cv2.imshow("men", img1)
cv2.waitKey(0)
#cv2.destroyAllWindows()

-1

In [4]:
#Viewing the black and white image image
cv2.imshow("men", img2)
cv2.waitKey(2000)
#cv2.destroyAllWindows()

-1

# Image resizing

In [8]:
#resizing the coloured image
resized_img= cv2.resize(img1, (300, 300))

In [9]:
cv2.imshow("men", resized_img)
cv2.waitKey(0)


-1

In [ ]:
#cv2.destroyAllWindows()

In [16]:
#resizing the black and white image
resized_img= cv2.resize(img2, (500, 500))
cv2.imshow("men", resized_img)
cv2.waitKey(0)

-1

In [36]:
#coloured image
resized_img2= cv2.resize(img1, (int(img1.shape[1]/2),int(img1.shape[0]/2)))
cv2.imshow("men", resized_img2)
cv2.waitKey(0)

-1

In [21]:
resized_img2= cv2.resize(img, (int(img.shape[1]*2),int(img.shape[0]*2)))
cv2.imshow("men", resized_img2)
cv2.waitKey(0)

-1

# Face Detection

In [10]:
face_cascade= cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

In [11]:
image= cv2.imread("C:/Users/Open user/Documents/AWARRI collection 2/3_men.jpg", 1)

In [12]:
image.shape

(1080, 1920, 3)

In [13]:
#Reading the image as a gray scale
gray_img= cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

In [14]:
#Perform face detection
faces= face_cascade.detectMultiScale(gray_img, scaleFactor= 1.05, minNeighbors=5)
print(faces)

[[ 220  200  274  274]
 [ 789  231  304  304]
 [1477  253  271  271]]


In [15]:
for x, y, w, h in faces:
    img= cv2.rectangle(image, (x,y), (x+w, y+h), (0, 255, 0), 3)
    resized= cv2.resize(img, (int(img.shape[1]/2),int(img.shape[0]/2)))
cv2.imshow("face_detection", resized)
cv2.waitKey(0)

-1

# Face detection 2

In [16]:
image2= cv2.imread("C:/Users/Open user/Documents/AWARRI collection 2/5_sport_men.jpg", 1)

#Reading the image as a gray scale
gray_img2= cv2.cvtColor(image2, cv2.COLOR_BGR2GRAY)

#Perform face detection
faces2= face_cascade.detectMultiScale(gray_img2, scaleFactor= 1.05, minNeighbors=5)
print(faces2)

[[ 287  123   38   38]
 [ 375  117   63   63]
 [1007   98   73   73]
 [ 270  427   62   62]
 [ 730  425   88   88]
 [ 183   85   64   64]
 [ 820   92   65   65]
 [ 791  242   62   62]
 [ 810  516  235  235]]


In [17]:
for x, y, w, h in faces2:
    img= cv2.rectangle(image2, (x,y), (x+w, y+h), (0, 255, 0), 3)
    resized2= cv2.resize(img, (int(img.shape[1]/2),int(img.shape[0]/2)))
cv2.imshow("face_detection2", resized2)
cv2.waitKey(0)

-1

# Face detection 3

In [18]:
images= cv2.imread("C:/Users/Open user/Downloads/Bola-Tinubu-11.webp", 1)

#Reading the image as a gray scale
gray_img3= cv2.cvtColor(images, cv2.COLOR_BGR2GRAY)

#Perform face detection
faces3= face_cascade.detectMultiScale(gray_img3, scaleFactor= 1.05, minNeighbors=5)
print(faces3)

[[141 110 434 434]]


In [23]:
for x, y, w, h in faces3:
    img= cv2.rectangle(images, (x,y), (x+w, y+h), (0, 255, 0), 3)
    resized3= cv2.resize(img, (int(img.shape[1]/2),int(img.shape[0]/2)))
cv2.imshow("face_detection2", resized3)
cv2.waitKey(0)

-1

In [20]:
image3= cv2.imread("C:/Users/Open user/Downloads/Sanwo-Olu-2.jpg")

#Reading the image as a gray scale
gray= cv2.cvtColor(image3, cv2.COLOR_BGR2GRAY)

#Perform face detection
faces4= face_cascade.detectMultiScale(gray, scaleFactor= 1.05, minNeighbors=5)
print(faces4)

[[170  49 209 209]]


In [111]:
image3.shape

(400, 600, 3)

In [22]:
for x, y, w, h in faces4:
    img= cv2.rectangle(image3, (x,y), (x+w, y+h), (0, 255, 0), 3)
    resized4= cv2.resize(img, (int(img.shape[1]/2),int(img.shape[0]/2)))
cv2.imshow("face_detection2", resized4)
cv2.waitKey(0)

-1

In [21]:
for x, y, w, h in faces4:
    img= cv2.rectangle(image3, (x,y), (x+w, y+h), (0, 255, 0), 3)
cv2.imshow("face_detection2", img)
cv2.waitKey(0)

-1